version: '3.7'
services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  cache:
    image: redis:6.0
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
  smtp:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
volumes:
  postgresql:
  redis: